on: [push]

jobs:
  test-python:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Install Python and pip
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install depencies
      run: pip install -r python/requirements.txt
    
    - name: Run tests
      run: pytest python/test.py
  
  test-js:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: node

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

